#include "stm32h7xx_hal.h"
#include <string.h>

// Function prototypes
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_TIM3_Init(void);
static void MX_USART3_UART_Init(void);

TIM_HandleTypeDef htim3;
UART_HandleTypeDef huart3;
uint8_t rx_buffer[10];

int main(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_TIM3_Init();
    MX_USART3_UART_Init();

    // Start UART reception in interrupt mode
    HAL_UART_Receive_IT(&huart3, rx_buffer, sizeof(rx_buffer));

    while (1) {
        // Main loop remains empty
    }
}

void SystemClock_Config(void) {
   void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Supply configuration update enable
  */
  HAL_PWREx_ConfigSupply(PWR_LDO_SUPPLY);

  /** Configure the main internal regulator output voltage
  */
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);

  while(!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY)) {}

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_DIV1;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2
                              |RCC_CLOCKTYPE_D3PCLK1|RCC_CLOCKTYPE_D1PCLK1;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
  RCC_ClkInitStruct.SYSCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB3CLKDivider = RCC_APB3_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_APB1_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_APB2_DIV1;
  RCC_ClkInitStruct.APB4CLKDivider = RCC_APB4_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
  {
    Error_Handler();
  }
} // System Clock Configuration
    // This function is typically generated by STM32CubeMX
    // Ensure it is configured to your specific needs
}

static void MX_TIM3_Init(void) {
    TIM_OC_InitTypeDef sConfigOC = {0};

    htim3.Instance = TIM3;
    htim3.Init.Prescaler = (SystemCoreClock / (115 * 256)) - 1; // Calculate prescaler for 115Hz
    htim3.Init.CounterMode = TIM_COUNTERMODE_UP;
    htim3.Init.Period = 255;
    htim3.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
    htim3.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
    HAL_TIM_PWM_Init(&htim3);

    sConfigOC.OCMode = TIM_OCMODE_PWM1;
    sConfigOC.Pulse = 127; // 50% duty cycle
    sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
    sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;

    // Configure PWM channels for motors
    HAL_TIM_PWM_ConfigChannel(&htim3, &sConfigOC, TIM_CHANNEL_1); // PC6
    HAL_TIM_PWM_ConfigChannel(&htim3, &sConfigOC, TIM_CHANNEL_2); // PB8
    HAL_TIM_PWM_ConfigChannel(&htim3, &sConfigOC, TIM_CHANNEL_3); // PB9
    HAL_TIM_PWM_ConfigChannel(&htim3, &sConfigOC, TIM_CHANNEL_4); // PB15

    // Configure PWM channels for LEDs
    HAL_TIM_PWM_ConfigChannel(&htim3, &sConfigOC, TIM_CHANNEL_1); // PB10
    HAL_TIM_PWM_ConfigChannel(&htim3, &sConfigOC, TIM_CHANNEL_2); // PB11
    HAL_TIM_PWM_ConfigChannel(&htim3, &sConfigOC, TIM_CHANNEL_3); // PA0
    HAL_TIM_PWM_ConfigChannel(&htim3, &sConfigOC, TIM_CHANNEL_4); // PB0
}

static void MX_GPIO_Init(void) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    // Enable GPIO Clocks
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOD_CLK_ENABLE();
    __HAL_RCC_GPIOE_CLK_ENABLE();
    __HAL_RCC_GPIOF_CLK_ENABLE();
    __HAL_RCC_GPIOG_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    // Configure GPIO pins for PWM output for motors
    GPIO_InitStruct.Pin = GPIO_PIN_6; // PC6
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF2_TIM3; // Adjust according to your timer
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_8 | GPIO_PIN_9 | GPIO_PIN_15; // PB8, PB9, PB15
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    // Configure GPIO pins for PWM output for LEDs
    GPIO_InitStruct.Pin = GPIO_PIN_10 | GPIO_PIN_11; // PB10, PB11
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_0; // PA0
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_0; // PB0
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    // Configure GPIO pins for control signals
    GPIO_InitStruct.Pin = GPIO_PIN_5; // PB5 for Ext1_EN
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_PULLDOWN;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_6; // PC6 for Ext1_Dir
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_14; // PD14 for Ext2_EN
    HAL_GPIO_Init(GPIOD, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_15; // PD15 for Ext2_Dir
    HAL_GPIO_Init(GPIOD, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_3; // PF3 for Feed1_EN
    HAL_GPIO_Init(GPIOF, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_12; // PG12 for Feed1_Dir
    HAL_GPIO_Init(GPIOG, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_9; // PE9 for Feed2_EN
    HAL_GPIO_Init(GPIOE, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_11; // PE11 for Feed2_Dir
    HAL_GPIO_Init(GPIOE, &GPIO_InitStruct);

    // Configure GPIO pins for light barrier inputs with interrupt
    GPIO_InitStruct.Pin = GPIO_PIN_14; // PF14 for LB1
    GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING;
    GPIO_InitStruct.Pull = GPIO_PULLDOWN;
    HAL_GPIO_Init(GPIOF, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_13; // PE13 for LB2
    HAL_GPIO_Init(GPIOE, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_14; // PG14 for LB3
    HAL_GPIO_Init(GPIOG, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_6; // PB6 for LB4
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    // Configure GPIO pins for UART3
    GPIO_InitStruct.Pin = GPIO_PIN_8 | GPIO_PIN_9; // PD8 RX, PD9 TX
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF7_USART3;
    HAL_GPIO_Init(GPIOD, &GPIO_InitStruct);

    // Enable and set EXTI line interrupt priority
    HAL_NVIC_SetPriority(EXTI15_10_IRQn, 2, 0);
    HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
}

static void MX_USART3_UART_Init(void) {
    huart3.Instance = USART3;
    huart3.Init.BaudRate = 115200;
    huart3.Init.WordLength = UART_WORDLENGTH_8B;
    huart3.Init.StopBits = UART_STOPBITS_1;
    huart3.Init.Parity = UART_PARITY_NONE;
    huart3.Init.Mode = UART_MODE_TX_RX;
    huart3.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart3.Init.OverSampling = UART_OVERSAMPLING_16;
    huart3.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
    huart3.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
    HAL_UART_Init(&huart3);
}

// UART receive complete callback
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart) {
    if (huart->Instance == USART3) {
        if (strncmp((char*)rx_buffer, "START", 5) == 0) {
            // Set Ext1_EN and Ext2_EN low
            HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_RESET); // Ext1_EN
            HAL_GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_RESET); // Ext2_EN

            // Set Ext1_Dir and Ext2_Dir high
            HAL_GPIO_WritePin(GPIOC, GPIO_PIN_6, GPIO_PIN_SET); // Ext1_Dir
            HAL_GPIO_WritePin(GPIOD, GPIO_PIN_15, GPIO_PIN_SET); // Ext2_Dir

            // Start PWM on Ext1 and Ext2 motor pins
            HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_1); // PC6 for Ext1
            HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_2); // PB8 for Ext2
        } else if (strncmp((char*)rx_buffer, "STOP", 4) == 0) {
            // Stop PWM on all motor and LED pins
            HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_1); // PC6 for Ext1
            HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_2); // PB8 for Ext2
            HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_3); // PB9 for Feed1
            HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_4); // PB15 for Feed2
            HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_1); // PB10 for L1
            HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_2); // PB11 for L2
            HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_3); // PA0 for L3
            HAL_TIM_PWM_Stop(&htim3, TIM_CHANNEL_4); // PB0 for L4

            // Optionally reset the direction and enable pins
            HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_SET); // Ext1_EN
            HAL_GPIO_WritePin(GPIOD, GPIO_PIN_14, GPIO_PIN_SET); // Ext2_EN
        }

        // Restart UART reception in interrupt mode
        HAL_UART_Receive_IT(&huart3, rx_buffer, sizeof(rx_buffer));
    }
}

// Interrupt handler for EXTI lines 10 to 15
void EXTI15_10_IRQHandler(void) {
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_14); // PF14 for LB1
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_13); // PE13 for LB2
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_14); // PG14 for LB3
    HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_6);  // PB6 for LB4
}

// Callback function for handling GPIO EXTI interrupts
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin) {
    if (GPIO_Pin == GPIO_PIN_14 || GPIO_Pin == GPIO_PIN_13 || GPIO_Pin == GPIO_PIN_14 || GPIO_Pin == GPIO_PIN_6) {
        // Set Feed1_EN and Feed2_EN low
        HAL_GPIO_WritePin(GPIOF, GPIO_PIN_3, GPIO_PIN_RESET); // Feed1_EN
        HAL_GPIO_WritePin(GPIOE, GPIO_PIN_9, GPIO_PIN_RESET); // Feed2_EN

        // Set Feed1_Dir and Feed2_Dir high
        HAL_GPIO_WritePin(GPIOG, GPIO_PIN_12, GPIO_PIN_SET); // Feed1_Dir
        HAL_GPIO_WritePin(GPIOE, GPIO_PIN_11, GPIO_PIN_SET); // Feed2_Dir

        // Start PWM on Feed1 and Feed2 motor pins
        HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_3); // PB9 for Feed1
        HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_4); // PB15 for Feed2

        // Start PWM on L1, L2, L3, and L4 for LEDs
        HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_1); // PB10 for L1
        HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_2); // PB11 for L2
        HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_3); // PA0 for L3
        HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_4); // PB0 for L4
    }
} 
